### ISSUE TITLE
No speech cyrillics

### ISSUE THREAD

**Issue by ThirtysixLab** [chcg/SpeechPlugin#16]
Hi!
Very useful plugin. Thank you!
I used this to check texts for typos. But in Cyrillic text only numbers are pronounced. (I also tried changing voices in Windows settings - nothing changes)

**Comment by chcg** [comment]
Maybe the transformation from UTF8 (N++) -> UTF16(windows used by SAPI) is missing or not done correct. That needs to be checked.

**Comment by chcg** [comment]
@ThirtysixLab Could you please test https://github.com/chcg/SpeechPlugin/releases/tag/v0.6.0. This release should fix the problem if used together with a voice capable to speak russian.

**Comment by ThirtysixLab** [comment]
Yes!
This is work! Awesome!
Thank you!
 
 
--
Best,
Alexey - ThirtysixLab ️ 2024

**Comment by ThirtysixLab** [comment]
What about (changing voices in Windows settings)? - still not work. Perhaps this can be implemented in a N++ interface?

**Comment by chcg** [comment]
@ThirtysixLab See https://github.com/chcg/SpeechPlugin/issues/10. Likely no impl from me soon.
